# TODO: I'll get to these during the API redesign

Metrics/AbcSize:
  Exclude:
    - 'lib/**/*'

Metrics/BlockNesting:
  Exclude:
    - 'lib/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/**/*'

Metrics/LineLength:
  Exclude:
    - 'lib/**/*'

Metrics/MethodLength:
  Exclude:
    - 'lib/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'lib/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/**/*'

Layout/LineLength:
  Exclude:
    - 'lib/**/*'
    - 'testing/rspec/spec/filter_example_spec.rb'
    - 'testing/rspec/spec/filter_feature_dsl_spec.rb'
    - 'testing/rspec/spec/filter_sso_spec.rb'
    - 'testing/rspec/spec/map_reduce_spec.rb'
    - 'testing/rspec/spec/select_scenario_dsl_spec.rb'
    - 'testing/rspec/spec/select_scen_outline_dsl_spec.rb'

Layout/LeadingCommentSpace:
  Exclude:
    - 'testing/rspec/spec/map_reduce_spec.rb'

Style/BracesAroundHashParameters:
  Exclude:
    - 'testing/rspec/spec/filter_sso_spec.rb'
