os:
  - linux
  - osx

# JRuby isn't working on the new default distribution
dist: trusty

language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.3.3
  - 2.4.0
  - jruby-9.1.7.0

matrix:
  exclude:
    # Travis does not provide 1.8.7 on OSX
  - rvm: 1.8.7
    os: osx
    # Travis does not provide 1.9.3 on OSX
  - rvm: 1.9.3
    os: osx
    # Ruby 2.3.x is currently broken on TravisCI for OSX and is no longer a supported Ruby version, anyway.
  - rvm: 2.3.3
    os: osx
    # CukeModeler 3.x requires at least Ruby 2.3
  - rvm: 1.8.7
    gemfile: testing/gemfiles/cuke_modeler3.gemfile
  - rvm: 1.9.3
    gemfile: testing/gemfiles/cuke_modeler3.gemfile


gemfile:
  - testing/gemfiles/cuke_modeler0.gemfile
  - testing/gemfiles/cuke_modeler1.gemfile
  - testing/gemfiles/cuke_modeler2.gemfile
  - testing/gemfiles/cuke_modeler3.gemfile

# todo - Remove this once TravisCI fixes their bundler issue (https://github.com/alphagov/govuk_template/pull/186)
before_install:
  - gem install bundler -v '< 2'

script: bundle exec rake cql:ci_build
