version: '1.0.{build}'

environment:
  matrix:
    - RUBY_VERSION: 187-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler0.gemfile
    - RUBY_VERSION: 193-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler0.gemfile
    - RUBY_VERSION: 200-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler0.gemfile
    - RUBY_VERSION: 21-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler0.gemfile
    - RUBY_VERSION: 22-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler0.gemfile

    - RUBY_VERSION: 187-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 193-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 200-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 21-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 22-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile


install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
