name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # Monthly

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby-version: ['2.1', '2.2', '2.3', '2.5', '2.7', '3.0', 'jruby-9.1.17.0']
        gemfile: [ cuke_modeler1, cuke_modeler2, cuke_modeler3 ]
        exclude:
          # CukeModeler 3.x requires at least Ruby 2.3
          - gemfile: cuke_modeler3
            ruby-version: '2.1'
          - gemfile: cuke_modeler3
            ruby-version: '2.2'
          # CukeModeler 1.x and 2.x do not support beyond Ruby 2
          - gemfile: cuke_modeler1
            ruby-version: '3.0'
          - gemfile: cuke_modeler2
            ruby-version: '3.0'
    runs-on: ${{ matrix.os }}
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: testing/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run CI Rake task
        run: bundle exec rake cql:test_everything
      - name: Check LCOV file
        run: less ./reports/coverage/lcov/lcov.info
      - name: Check JSON file
      - run: less ./reports/coverage/.last_run.json
      - name: Check Gemfile file
      - run: less Gemfile    # Sanity check
      - name: Push code coverage to Coveralls (conditional)
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: "./reports/coverage/lcov/lcov.info"
          parallel: true
          flag-name: run-${{ matrix.os }}-${{ matrix.ruby-version }}-${{ matrix.gemfile }}
        if: matrix.ruby-version != '2.3' && matrix.ruby-version != 'jruby-9.1.17.0'

  test_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  check_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake cql:check_documentation

  lint_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake cql:rubocop
